### PR TITLE
MAINT: fix plugin registration so that plugin is discoverable

### PR DESCRIPTION
**Pull request by jairideout**
Plugin registration is working so that the plugin and its command is available from the framework's plugin manager and interfaces (e.g. q2cli).

@ConstantinoSchillebeeckx can you test this out by running:

``` bash
$ qiime phylogram make_d3_phylogram --help
```

Running `make_d3_phylogram` raises some errors because there's some issues with the business logic in the function. I tried fixing the issues but wasn't able to in a few minutes. @ConstantinoSchillebeeckx I think you're the best one to fix those. `make_d3_phylogram` now accepts a Biopython `Tree` object as its `tree` parameter and a `qiime.Metadata` object as its `otu_metadata` parameter, which gets converted to a pandas `DataFrame` in the first line of the function.

If you're testing this from the command line, you'll need to import a newick file into an artifact, e.g.:

``` bash
$ qiime tools import --type Phylogeny --input-path example.newick --output-path tree.qza
```

You can then run your plugin command:

``` bash
$ qiime phylogram make_d3_phylogram --tree tree.qza --otu-metadata-file otu-metadata.txt --visualization viz.qzv
```

We'll be adding a "feature metadata" type in the next few days so that `otu-metadata` can be an artifact. For now we're accepting QIIME 1's "sample metadata" file format so you're able to test your plugin.

Let me know if you have any questions about the changes and if we can help with anything! We'll let you know when a "feature metadata" type is ready and can help you update your plugin then.

### CODE REVIEW

**Comment by ConstantinoSchillebeeckx** [comment]
I've done the following to re-install the plugin:

```
rm -rf ~/miniconda2/envs/q2test/lib/python3.5/site-packages/q2_phylogram*
pip install https://github.com/ConstantinoSchillebeeckx/q2-phylogram/archive/master.zip --upgrade
```

I can confirm the plugin installs:
`Successfully installed pytz-2016.6.1 q2-phylogram-0.0.0.dev0`
However when I do  `qiime phylogram make_d3_phylogram --help`, I get:

```
Usage: qiime [OPTIONS] COMMAND [ARGS]...

Error: No such command "phylogram".
```

Furthermore, the plugin doesn't list when I do `qiime --plugin`.  What am I doing wrong?  Thanks for your patience!

**Comment by jairideout** [comment]
Don't uninstall conda packages that way, use `conda uninstall -n <package-name>`. That might have something to do with the issues you're having. Can you run `conda uninstall -n q2-phylogram` and then install your plugin in "development" mode (removes the need to reinstall after every code edit):

``` bash
pip install -e .
```

You'll need to be in the root directory of your q2-phylogram repo for this last command.

**Comment by ConstantinoSchillebeeckx** [comment]
I'm new to writing packages, so I'm having difficulty getting all of this to work.

I installed QIIME2 on a different computer (Ubuntu) and was able to confirm it installed properly (`qiime info`).  Then I copied my q2-phylogram repo into `~/miniconda2/envs/q2test/lib/python3.5/site-packages/` and ran `pip install -e .` from inside that directory; I got the following response:

```
Successfully built biopython
Installing collected packages: biopython, q2-phylogram
  Running setup.py develop for q2-phylogram
Successfully installed biopython-1.67 q2-phylogram
Cache entry deserialization failed, entry ignored
```

`qiime info` shows me:

```
System versions
Python version: 3.5.2
QIIME version: 2.0.1
q2cli version: 0.0.1

Installed plugins
feature-table 0.0.1 (https://github.com/qiime2-plugins/q2-feature-table)
types 0.0.1 (https://github.com/qiime2/q2-types)
```

However `conda list` shows me:

```
q2-feature-table          0.0.1                    py35_0    qiime2
q2-phylogram (/home/code_repo/python/q2-phylogram) 0.0.0.dev0                <pip>
q2-types                  0.0.1                    py35_0    qiime2
q2cli                     0.0.1                    py35_0    qiime2
qiime                     2.0.1                    py35_0    qiime2
```

Furthermore, I'm still getting `Error: No such command "phylogram".`

**Comment by jairideout** [comment]
Here's how I recommend setting up your dev environment:
1. Remove your current conda environment.
2. Install the latest version of QIIME 2 and the available plugins following the [wiki instructions](https://github.com/qiime2/qiime2/wiki/Installing-and-using-QIIME-2).
3. From your cloned `q2-phylogram` repo (which can live anywhere on your filesystem), run `pip install -e .`. This will install your package into the conda environment you created in step 2 in "development" mode so you don't need to reinstall every time you make changes to your code. You don't need to copy anything into `~/miniconda2/envs/q2test/lib/python3.5/site-packages/`. You shouldn't modify conda's site-packages because conda is managing that for you.

Let me know how it goes!

**Comment by ConstantinoSchillebeeckx** [comment]
Now we're cooking with some heat! 🔥 

I've been able to successfully install the plugin and have [made fixes](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/commit/d3ce3ee3162fda62caa3396c6314e9d13012a086) to the business logic.

There's just one more thing that I'm not grasping: the output of files. The [wiki](https://github.com/qiime2/qiime2/wiki/Creating-a-QIIME-2-plugin#create-a-function-that-will-be-registered-as-a-visualizer) mentions: 

> Next, at least one index.\* file must be written to output_dir by the function.

As you [can see](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/master/q2_phylogram/plugin_setup.py#L103:L104), I'm writing the `index.html` file to the output_dir (along with `/dat` which contains the Newick tree and the leaf metadata).

What am I missing?

Finally, on another note, I've had to change the header of my [otu_metadata file](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/master/example/mapping.txt) so that it conforms to the mapping file rules (e.g. #SampleID as the first header column).  I imagine when the "feature metadata" artifact is defined, this header could be something other than the currently required one.

Thanks for your continued support on this!

**Comment by ebolyen** [comment]
Hey @ConstantinoSchillebeeckx, it looks like your code is essentially correct from the plugin standpoint. 

What is breaking things now is the AJAX call to a `file://` resource. If you go to the temp directory created by `qiime tools view` you can run `python -m http.server` and opening a browser to `localhost:8000` you will see all of your assets are there and it all runs (Super cool, btw!). 

What is happening is the [cross-origin resource policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) is getting in the way (and for good reason). This prevents websites from sniffing your filesystem and doing other unscrupulous things, but it often gets in the way even for innocuous use cases. 

The easiest way to get rolling would be to use a technique called [JSONP](http://stackoverflow.com/a/2067584/579416) where you wrap the data into a function call such that when loaded from a `<script>` tag, the data is sent to a callback which exists in the main page, from there you can do whatever is needed. It is important to note that it isn't possible to set the `CORS` headers to load across domains as you aren't actually using an `HTTP` protocol, that's what the `file://` is all about.

I have a toy-plugin which uses this technique:
First the [JSONP file needs to be written](https://github.com/ebolyen/q2-gba/blob/08c20786bb9a1e741310ffc940347693af06e712/q2_gba/plugin_setup.py#L64-L65), then the [callback needs to be defined](https://github.com/ebolyen/q2-gba/blob/08c20786bb9a1e741310ffc940347693af06e712/q2_gba/assets/index.html#L260-L262), and finally [the JSONP file must be loaded via a script tag](https://github.com/ebolyen/q2-gba/blob/08c20786bb9a1e741310ffc940347693af06e712/q2_gba/assets/index.html#L331). (I had to base64 encode because ROM's are binary, but you don't need to do that step (although it would make escaping text a non-concern))

**Comment by ConstantinoSchillebeeckx** [comment]
Thanks @ebolyen for educating me on some web-dev policy.  I've always wondered why my developer tools were giving me that warning. 😏 

I stumbled upon this [JSONP plugin for D3](https://github.com/d3/d3-plugins/tree/master/jsonp), which I've incorporated in the plugin.  As for the mapping file, I'm writing that directly to the index.html file as a javascript var.

It looks like the plugin is working at this point (at least on my end).  Thanks everyone for your help and the education!

**Pull request merged**
